import type { Metadata } from "next";
import { Quattrocento, Noto_Sans } from "next/font/google";
import { newIconSerif, newIconScript } from "@/fonts";
import "./globals.css";

const quattrocento = Quattrocento({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-quattrocento",
});

const notoSans = Noto_Sans({
  subsets: ["latin"],
  variable: "--font-noto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${quattrocento.variable} ${newIconSerif.variable}  ${newIconScript.variable} ${notoSans.variable}
 `}>
      <body>{children}</body>
    </html>
  );
}
