import type { Metadata } from "next";
import { Quattrocento } from "next/font/google";
import { newIconSerif, newIconScript } from "@/fonts";
import "./globals.css";

const quattrocento = Quattrocento({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-quattrocento",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${quattrocento.variable} ${newIconSerif.variable}  ${newIconScript.variable}
 `}>
      <body>{children}</body>
    </html>
  );
}
